language: php

php:
- 5.6

sudo: false

before_script:
- "./composer.phar install --dev --prefer-source --no-interaction"

script:
- "./vendor/bin/phpcs --standard=psr2 ./src"
- "./vendor/bin/phpmd src/ text codesize,controversial,design,naming,unusedcode"
- "./vendor/bin/phpunit"

# travis should only notify us if the build fails
notifications:
  email:
    on_success: never

env:
  global:
  - secure: V7P/r9fXv4TLEgj6iLZHdXehVJIhWc8RdOidGNkyY12sDsUYY9by20yjM4YVLnB/nLfpQmf4Lv1DAUvs6ZIc/j55tSi8/mjNPvpYNb/jzSvwzOuDQb6WIAFopiO+6tiyeGKvQs26KQuQwp4u1TsaO/f6+1TGK2hJaZ8nZ/AFN8I=
  - secure: ldqTMP/f0Ye5wEhta3DzwcSBhOTncf5rVgrDp9ArZva5c2DtCsdGki9X7tC9MTVki1uAffavCXvoeXA/fPYM5+a6F1NO6cvwykTkyotDLDhdKHdrgDw3P/soR+1JZfBMDyKmFMDfh7+oFqDolloYPOyp5pVDkj2s1emZJyIYpbU=

branches:
  only:
  - master
  - /^v\d+$/

deploy:
# playground
- provider: opsworks
  app-id: dc20bc97-ea19-48d1-ae1f-fab9a3213828
  on:
    branch: master
    repo: easybiblabs/easybib-discover-api
# production
- provider: opsworks
  app-id: dc2cd382-d891-41b1-aac7-3bf57bd81441
  on:
    tags: true
    repo: easybiblabs/easybib-discover-api
