language: php

php:
 - 5.6

sudo: false

before_script:
  - ./composer.phar install --dev --prefer-source --no-interaction

script:
  - ./vendor/bin/phpcs --standard=psr2 ./src
  - ./vendor/bin/phpmd src/ text codesize,controversial,design,naming,unusedcode
  - ./vendor/bin/phpunit

# travis should only notify us if the build fails
notifications:
  email:
    on_success: never
  hipchat:
    rooms:
      secure: IWV33y3to2IlsurFRpduF4Ei5Ydve1KKSGnp9r8+7YQ+HOxiuPra6uHq3iMmjKh4J+j7K+a7QOhJ9C+wGHiuUIY1hB6JQwz4DKd+M3C54Ii6nQGs3NifMM//XwuMCtWrHwNk2MmGF7Hec+NS95nfRKzpSRg+gpCROQ6YYxwGAw4=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html

deploy:
  # deploy new pushes to branch master to the staging environment
  - provider: script
    script: scripts/deploy.sh staging
    on:
      branch: master
  # deploy new tagged branches to production
  - provider: script
    script: scripts/deploy.sh production
    on:
      tags: true
      all_branches: true
