language: php

matrix:
  include:
    - php: 5.6
      env: MATRIX_JOB=php-test-56
    - php: 7.0
      env: MATRIX_JOB=php-test-7
    - php: 7.0
      env: MATRIX_JOB=deploy

before_script:
  - ./composer.phar install --dev --prefer-source --no-interaction

script:
  - ./vendor/bin/phpcs --standard=psr2 ./src
  - ./vendor/bin/phpmd src/ text codesize,controversial,design,naming,unusedcode
  - ./vendor/bin/phpunit

# travis should only notify us if the build fails
notifications:
  email:
    on_success: never
  hipchat:
    rooms:
      secure: WwFdxXzbljYaFeKBr2JQ6fmS3/0QiOn6U/+HPpVpvaMBQws5Fxpxh4YeU7K1vXGLGbr2VGTywSk5YBAOA3tnf7orzuMicP4IsU4X1Q5rbz6kTj1qIgiGoJQ1rHDWMIwVnYiiy7IPN/QRtHFTUqFdL+gVZHoPHHiveoaADn2y1+0=
    template:
      - 'This is a test %{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html

deploy:
  # deploy new pushes to branch master to the staging environment
  - provider: script
    script: scripts/deploy.sh staging
    on:
      branch: master
      condition: $MATRIX_JOB = deploy
  # deploy new tagged branches to production
  - provider: script
    script: scripts/deploy.sh production
    on:
      tags: true
      all_branches: true
      condition: $MATRIX_JOB = deploy
