version: "2"
services:
    discover:
        build:
            dockerfile: ./docker/Dockerfile-discover
            context: .
        environment:
            - APP_FUNCTION=DISCOVER
            - APP_ENVIRONMENT=DEVELOPMENT
            - APPNAME=discover
            - DOMAINS=discover.data.easybib.bib
            - STACK_ENVIRONMENT=vagrant
            - STACK_NAME=convox
            - OAUTH_URL_ID=http://id.easybib.bib
            - OAUTH_URL_DATA=http://data.easybib.bib
            - OAUTH_SECRET=local-vagrant-api-secret
            - QAFOO_PROFILER_KEY=
        labels:
            - convox.port.443.protocol=https
        ports:
            - 80:80
            - 443:80
